Name:           ros-kinetic-arbotix-sensors
Version:        0.10.0
Release:        1%{?dist}
Summary:        ROS arbotix_sensors package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/arbotix_sensors
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-arbotix-python
BuildRequires:  ros-kinetic-catkin

%description
Extends the arbotix_node package with a number of more sophisticated ROS
wrappers for common devices.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Apr 03 2018 Michael Ferguson <mike@vanadiumlabs.com> - 0.10.0-1
- Autogenerated by Bloom

* Mon Jun 19 2017 Michael Ferguson <mike@vanadiumlabs.com> - 0.10.0-0
- Autogenerated by Bloom

